# Site settings
title: Patrick Johnson
email: im@pbj.me
description: Patrick Johnson is a front-end developer working in New York City. He helps companies build websites and bakes delicious cookies.
baseurl: "" # the subpath of your site, e.g. /blog/
imgurl: '/uploads/'
url: "http://pbj.me" # the base hostname & protocol for your site
twitter: patrickbjohnson
github:  patrickbjohnson
dribbble:  pbj
linkedin:  patrickbjohnson

# Collections
collections:
  work:
    output: true
  goals: 
    output: true


# Build settings
markdown: kramdown
gems: [bourbon, neat]