# Site settings
title: Patrick Johnson
email: your-email@domain.com
description: This is a site description. Change this in the _config.yml file.
baseurl: "" # the subpath of your site, e.g. /blog/
imgurl: '/uploads/'
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
bio: I'm a Front-End developer in New York City. I like to bake cookies. 

# Collections
collections:
  work:
    output: true
  goals: 
    output: true


# Build settings
markdown: kramdown
gems: [bourbon, neat]